### ISSUE TITLE
Error: linking with `cc` failed: exit code: 1

### ISSUE THREAD

**Issue by Chococoin** [MacTuitui/nannou-universe#1]
Hi @MacTuitui,

I've really enjoyed your presentation at #GitHubUniverse2020.

I have rust installed with the version "rustc 1.47.0 (18bf6b4f0 2020-10-07)"

The traceback finish with this explanation.

```
Caused by:
process didn't exit successfully: `rustc --crate-name universe --edition=2018 src/main.rs --error-format=json --json=diagnostic-
rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no -C metadata=29f280a26f574133 -C
extra-filename=-29f280a26f574133 --out-dir /home/german/nannou-universe/target/release/deps -L
dependency=/home/german/nannou-universe/target/release/deps --extern nannou=/home/german/nannou-
universe/target/release/deps/libnannou-2847ec53d951e592.rlib -L native=/usr/lib/x86_64-linux-gnu` (exit code: 1)

```

What I did wrong?

Thank you for your help.

**Comment by MacTuitui** [comment]
Hi and thanks for the nice words!

Sorry for starting from the very top, but does it happen if you try to create a new binary with rust:
'''
cargo new --bin testbin
cd testbin
cargo run
'''

Or is it happening only when you add nannou as a dependency? If that's the case, are you using vulkan compatible drivers? 

It's surely a simple fix of missing a core system library somewhere, but let's find what is missing first :)

**Comment by kuroskuro** [comment]
Hi,
really enjoyed your presentation as well!
I think I ran into the same issue and was able to fix it by installing `libxcb-render-util0-dev`, `libxcb-shape0-dev` and `libxcb-xfixes0-dev` as described [here](https://github.com/amethyst/amethyst/issues/1471) on pop-os 5.11.0. 
My traceback was:
```  = note: /usr/bin/ld: cannot find -lxcb-render
          /usr/bin/ld: cannot find -lxcb-shape
          /usr/bin/ld: cannot find -lxcb-xfixes
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error; 3 warnings emitted

error: could not compile `universe`

Caused by:
  process didn't exit successfully: `rustc --crate-name universe --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no -C metadata=3b9525f552a74816 -C extra-filename=-3b9525f552a74816 --out-dir /home/skuro/code/nannou-universe/target/release/deps -L dependency=/home/skuro/code/nannou-universe/target/release/deps --extern nannou=/home/skuro/code/nannou-universe/target/release/deps/libnannou-62ae2b6c931f37a5.rlib -L native=/usr/lib/x86_64-linux-gnu` (exit code: 1)
```

**Comment by Chococoin** [comment]
Thank you!
