### ISSUE TITLE
Cannot get the screen update to happen as fast/smoothly as you showed

### ISSUE THREAD

**Issue by kn27** [MacTuitui/nannou-universe#2]
Hi there,

Great presentation! I am new to both Rust and nannou, I tried to replicate your code and wonder why the rendered visualization is refreshing at a much slower rate than yours. For example, in the part where all the points moved to the right, the speed on your screen was at least 10 times after than on mine. 

Is there any setting for the refresh rate? I tried to add app.set_loop_mode(LoopMode::rate_fps(1000.0)); to fn model(app: &App) -> Model but it doesn't really change anything.

Thank you!

**Comment by MacTuitui** [comment]
Thanks a lot! 
Two things: try reducing the number of things, then try to reduce the complexity of the ellipses by adding `.resolution(10)` or so. The rasterizer will have far less work to do (but when you get to the lines it should be fast enough, no?) and you should be fine. That part (computing the vertices for all the shapes) is actually still done on the cpu so if you have issues here I'd say it is just too much for you cpu to handle. That said, this does not really needs that many detailed shapes...

There is an issue with winit/wgpu where you can not actually set a desired frame rate right now: https://github.com/nannou-org/nannou/issues/708 if you want to follow.

**Comment by kn27** [comment]
Hi Alexis,

Thank you for your answer! Somehow my Rust setup failed to compile with
this error "linking with `cc` failed" after I reinstalled the nvidia driver
yesterday ... so I haven't got a chance to test out your suggestion.

A few more questions if you don't mind!

1. In terms of user inputs, does nannou have the functionality like ml5js
to capture, say, hand motion inputs for example? Is it possible to plug in
a posenet model written in Python to capture the hand motion input, which
then allows you to interact with your visual art?
2. Do you have any suggestions for good tutorials (like yours, I wish you
did a series!) for creative coding beginners?

Thank you again for your help!

Cheers,
Keane

**Comment by patgarner** [comment]
I'm trying to run this code as is on a recent, high end, Intel Macbook Pro and it crawls, super, super slow. Like shockingly slow. Far, far slower than it runs in your demo from 2020! I can literally see it add each frame.

**Comment by patgarner** [comment]
Nevermind, I completely failed to see that you ran explicitly with --release ever time and of course when I do that it makes a massive difference in performance. Thanks for the presentation!
